[output]
# For packing_task, z_offset_up = 0.15 in place, and z_offset_up/down = 0.035,0.015 respectively for pick
taskname = "engine_parts_to_box_single_list"
directory = "./data/"

[tool_controlkeys]
rgb = "a"
depth = "d"
snapshot = "s"
clear_pick = "1"
clear_place = "2"
save = "x"
lang_goal = "i"
quit = "q"
pick = "p"
place = "l"
open_gripper = "o"
close_gripper = "k"
home = "h"
stop_execution = "b"
recover_robot = "z"
add_step = "c"
clear_all = "3"

[viewer_controlkeys]
rgb = "a"
depth = "d"
next = "l"
previous = "j"
quit = "q"

[taskexecutor]
enable = true
enable_gripper = true
